// frontend/src/app/profile/_components/copy.ts
// Single source of truth for all profile-section translations.
// Usage: import { PROFILE_COPY } from "./copy";
//        const copy = PROFILE_COPY[language];

export const PROFILE_COPY = {
  fr: {
    // ── Tabs panel ──────────────────────────────────────────────────────────
    tabs: {
      formation:  "Formation",
      experience: "Expérience",
      skills:     "Compétences",
      langues:    "Langues",
    },
    add:              "Ajouter",
    skills:           "Compétences techniques",
    experience:       "Expérience professionnelle",
    formation:        "Formation",
    langues:          "Langues",
    emptySkills:      "Aucune compétence ajoutée",
    emptyExp:         "Aucune expérience ajoutée",
    emptyForm:        "Aucune formation ajoutée",
    emptyLang:        "Aucune langue ajoutée",
    present:          "Présent",
    deleted:          "Supprimé",
    deleteSkillSuccess:"Compétence supprimée",
    deleteError:      "Erreur lors de la suppression",
    error:            "Erreur",

    // ── AddLangueModal ───────────────────────────────────────────────────────
    langueModal: {
      addTitle:   "Ajouter une langue",
      editTitle:  "Modifier la langue",
      langLabel:  "Langue",
      langPlaceholder: "Français, Anglais, Arabe…",
      niveauLabel: "Niveau",
      addBtn:     "Ajouter",
      editBtn:    "Modifier",
      successAdd: "Langue ajoutée",
      successEdit:"Modifié",
      errorMsg:   "Erreur",
    },

    // ── AddSkillModal ────────────────────────────────────────────────────────
    skillModal: {
      title:       "Ajouter une compétence",
      skillLabel:  "Compétence",
      skillPlaceholder: "React, Python, Figma…",
      levelLabel:  "Niveau",
      beginner:    "Débutant",
      intermediate:"Intermédiaire",
      expert:      "Expert",
      searchPlaceholder: "Rechercher ou saisir une compétence…",
      useValue:    "Utiliser",
      alreadyInList:"Déjà dans la liste",
      noResults:   "Aucun résultat",
      beginnerShort:"Débutant",
      expertShort: "Expert",
      addAction:   "Ajouter",
      enterSkillAbove:"Saisir une compétence ci-dessus",
      toAdd:       "À ajouter",
      saving:      "Enregistrement…",
      addAtLeastOne:"Ajoutez au moins une compétence",
      confirm:     "Confirmer",
      skillSingular:"compétence",
      skillPlural: "compétences",
      successAdd:  "Compétence ajoutée",
      errorMsg:    "Erreur",
    },

    // ── AddExperienceModal ───────────────────────────────────────────────────
    expModal: {
      addTitle:    "Ajouter une expérience",
      editTitle:   "Modifier l'expérience",
      posteLabel:  "Poste",
      postePlaceholder: "Développeur Front-end…",
      entrepriseLabel: "Entreprise",
      entreprisePlaceholder: "Google, Startup XYZ…",
      dateDebutLabel: "Date de début",
      dateFinLabel:   "Date de fin",
      actuelLabel:    "Poste actuel",
      descLabel:      "Description",
      descPlaceholder:"Décrivez vos missions…",
      addBtn:         "Ajouter",
      editBtn:        "Modifier",
      successAdd:     "Expérience ajoutée",
      successEdit:    "Modifié",
      errorMsg:       "Erreur",
    },

    // ── AddFormationModal ────────────────────────────────────────────────────
    formModal: {
      addTitle:    "Ajouter une formation",
      editTitle:   "Modifier la formation",
      diplomeLabel: "Diplôme",
      diplomePlaceholder: "Master, Licence, Bac+2…",
      ecoleLabel:   "École / Université",
      ecolePlaceholder: "Université Mohammed V…",
      anneeLabel:   "Année d'obtention",
      anneePlaceholder: "2023",
      addBtn:       "Ajouter",
      editBtn:      "Modifier",
      successAdd:   "Formation ajoutée",
      successEdit:  "Modifié",
      errorMsg:     "Erreur",
    },
    editProfileModal: {
      title: "Modifier le profil",
      firstName: "Prénom",
      lastName: "Nom",
      titleLabel: "Titre professionnel",
      bio: "Bio",
      phone: "Téléphone",
      location: "Localisation",
      save: "Enregistrer",
      success: "Profil mis à jour",
      error: "Erreur lors de la mise à jour",
    },
  },

  en: {
    // ── Tabs panel ──────────────────────────────────────────────────────────
    tabs: {
      formation:  "Education",
      experience: "Experience",
      skills:     "Skills",
      langues:    "Languages",
    },
    add:              "Add",
    skills:           "Technical skills",
    experience:       "Work experience",
    formation:        "Education",
    langues:          "Languages",
    emptySkills:      "No skills added yet",
    emptyExp:         "No experience added yet",
    emptyForm:        "No education added yet",
    emptyLang:        "No languages added yet",
    present:          "Present",
    deleted:          "Deleted",
    deleteSkillSuccess:"Skill deleted",
    deleteError:      "Error while deleting",
    error:            "Error",

    // ── AddLangueModal ───────────────────────────────────────────────────────
    langueModal: {
      addTitle:    "Add a language",
      editTitle:   "Edit language",
      langLabel:   "Language",
      langPlaceholder: "French, English, Arabic…",
      niveauLabel: "Level",
      addBtn:      "Add",
      editBtn:     "Save",
      successAdd:  "Language added",
      successEdit: "Saved",
      errorMsg:    "Error",
    },

    // ── AddSkillModal ────────────────────────────────────────────────────────
    skillModal: {
      title:       "Add a skill",
      skillLabel:  "Skill",
      skillPlaceholder: "React, Python, Figma…",
      levelLabel:  "Level",
      beginner:    "Beginner",
      intermediate:"Intermediate",
      expert:      "Expert",
      searchPlaceholder: "Search or type a skill…",
      useValue:    "Use",
      alreadyInList:"Already in the list",
      noResults:   "No results",
      beginnerShort:"Beginner",
      expertShort: "Expert",
      addAction:   "Add",
      enterSkillAbove:"Type a skill above",
      toAdd:       "To add",
      saving:      "Saving…",
      addAtLeastOne:"Add at least one skill",
      confirm:     "Confirm",
      skillSingular:"skill",
      skillPlural: "skills",
      successAdd:  "Skill added",
      errorMsg:    "Error",
    },

    // ── AddExperienceModal ───────────────────────────────────────────────────
    expModal: {
      addTitle:    "Add experience",
      editTitle:   "Edit experience",
      posteLabel:  "Job title",
      postePlaceholder: "Front-end Developer…",
      entrepriseLabel: "Company",
      entreprisePlaceholder: "Google, Startup XYZ…",
      dateDebutLabel: "Start date",
      dateFinLabel:   "End date",
      actuelLabel:    "Current position",
      descLabel:      "Description",
      descPlaceholder:"Describe your responsibilities…",
      addBtn:         "Add",
      editBtn:        "Save",
      successAdd:     "Experience added",
      successEdit:    "Saved",
      errorMsg:       "Error",
    },

    // ── AddFormationModal ────────────────────────────────────────────────────
    formModal: {
      addTitle:    "Add education",
      editTitle:   "Edit education",
      diplomeLabel: "Degree",
      diplomePlaceholder: "Master's, Bachelor's, Associate's…",
      ecoleLabel:   "School / University",
      ecolePlaceholder: "Harvard University…",
      anneeLabel:   "Graduation year",
      anneePlaceholder: "2023",
      addBtn:       "Add",
      editBtn:      "Save",
      successAdd:   "Education added",
      successEdit:  "Saved",
      errorMsg:     "Error",
    },
    editProfileModal: {
      title: "Edit profile",
      firstName: "First name",
      lastName: "Last name",
      titleLabel: "Professional title",
      bio: "Bio",
      phone: "Phone",
      location: "Location",
      save: "Save",
      success: "Profile updated",
      error: "Update failed",
    },
  },
} as const;
